[project]
name = 'bringo_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.anonymization]
path = 'contracts/anonymization.clar'
clarity_version = 2
epoch = 2.5

[contracts.community_contract]
path = 'contracts/community_contract.clar'
clarity_version = 2
epoch = 2.5

[contracts.data_marketplace]
path = 'contracts/data_marketplace.clar'
clarity_version = 2
epoch = 2.5

[contracts.decentralized_identity]
path = 'contracts/decentralized_identity.clar'
clarity_version = 2
epoch = 2.5

[contracts.fund_distribution]
path = 'contracts/fund_distribution.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
