[project]
name = 'bringo_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.anonymization]
path = 'contracts/anonymization.clar'
clarity_version = 2
epoch = 2.5

[contracts.community_contract]
path = 'contracts/community_contract.clar'
clarity_version = 2
epoch = 2.5

[contracts.data_marketplace]
path = 'contracts/data_marketplace.clar'
clarity_version = 2
epoch = 2.5

[contracts.decentralized_identity]
path = 'contracts/decentralized_identity.clar'
clarity_version = 2
epoch = 2.5

[contracts.fund_distribution]
path = 'contracts/fund_distribution.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage_node_registry]
path = 'contracts/storage_node_registry.clar'
clarity_version = 2
epoch = 2.5

[contracts.vault_with_increment_or_decrement]
path = 'contracts/vault_with_increment_or_decrement.clar'
clarity_version = 2
epoch = 2.5

[contracts.vote_delegation]
path = 'contracts/vote_delegation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
